apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1

      - name: Run gosec
        uses: cloudbees-io/gosec-sast-scan-code@v1
        kind: scan
        with:
          language: LANGUAGE_GO
